# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.0.0a2"
pantsd = true  # Enable the Pants daemon for better performance.

backend_packages.add = [
  'pants.backend.awslambda.python',
  # 'pants.backend.codegen.protobuf.python',
  'pants.backend.python',
  'pants.backend.python.lint.docformatter',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
  "toolchain.pants.auth",
  "toolchain.pants.buildsense",
  "toolchain.pants.common",
]
plugins = [
  "toolchain.pants.buildsense.plugin @ file:///Users/asher/projects/toolchain/dist/toolchain.pants.buildsense.plugin-0.0.2.tar.gz"
]

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]

[python-setup]
# The default interpreter compatibility for code in this repo. Individual targets can ovverride
#  this with the `compatibility` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.
interpreter_constraints = [">=3.7"]
# Use a lockfile. See https://www.pantsbuild.org/docs/python-third-party-dependencies.
requirement_constraints = "constraints.txt"

# [protoc]
# runtime_targets = ["//:protobuf"]

[flake8]
config = ".flake8"

[isort]
config = [".isort.cfg"]

[python-infer]
imports = false

streaming_workunits_handlers = ["toolchain.pants.buildsense.reporter.Reporter"]
streaming_workunits_report_interval = 1

[run-tracker]
stats_option_scopes_to_record = ["GLOBAL"]
stats_version = 2

[toolchain-setup]
repo = "example-python"

[auth]
base_url = "http://localhost:9500/api/v1"
# auth_file = ".pants.d/toolchain_auth/auth-dev.json"

[buildsense]
base_url = "http://localhost:9500/api/v1/repos/"
timeout = 10
